### ISSUE TITLE
README.mdのURLを変更してもらえると嬉しいです。

### ISSUE THREAD

**Issue by k896951** [poslogithub/binary-dist#1]
毎回利用してもらっているAssistantSeikaの作者です。
サイトの移動がありましたため、URLを変更してもらえると嬉しいです。

https://hgotoh.jp/wiki/doku.php/documents/voiceroid/assistantseika/assistantseika-001a
https://hgotoh.jp/wiki/doku.php/documents/voiceroid/assistantseika/assistantseika-000#%E5%AF%BE%E5%BF%9C%E8%A3%BD%E5%93%81
↓
https://wiki.hgotoh.jp/documents/tools/assistantseika/assistantseika-001a
https://wiki.hgotoh.jp/documents/tools/assistantseika/assistantseika-000#%E5%AF%BE%E5%BF%9C%E8%A3%BD%E5%93%81

**Comment by poslogithub** [comment]
ご連絡ありがとうございます。
変更しました。
